class Provider {
  final List<String> business_type = [
    "Individual Professional",
    "Shop/Store",
    "Retail Outlet",
    "Wholeseller",
    "Dealer",
    "Distributor",
    "Manufacturers",
    "Importer/Exporter",
    "Medical Services",
    "Hospitality & Food Services",
    "Educational Services",
    "Service provider",
    "Online Business",
  ];

  final Map<String, List<String>> business_category = {
    "Daily Home Needs": [
      "Grocery & General Stores",
      "Fruits & Vegetable Shops",
      "Milkman - Dudhwala",
      "Dairy farm",
      "Dairy Product Store",
      "Drinking Water & Cold Drinks",
      "Cooking Gas Agencies",
      "Laundry & Dry Cleaners",
      "Festivals, Rituals & Worship Needs",
      "Scrap Buyers & Dealers",
      "Tiffin Service",
      "Petrol Pump & CNG Pump",
      "Home Rent",
      "Shopping Mall",
      "Cable TV Operators & DTH Services",
      "Newspaper distributors",
      "Hawker( Pheri wala)",
      "CSC Centre & photocopy store"
    ],
    "Electronics, Kitchen & Home Appliances": [
      "Electronics Shops & Dealers",
      "Home, Kitchen Appliances & Electronic Stores",
      "Steel & Brass items Store",
      "Home Decor & Home Furnishing",
      "Kitchenware & Household Plastic Items",
      "Modular Kitchens",
      "Pest Control Service",
      "Electronics & Home Appliances Service Center",
      "Silai(Sewing) Machine Store",
    ],
    "Electricals & Lights": [
      "Electrical Shops & Dealers",
      "Lights, Chandeliers, Decorative & Fancy Lights",
      "Industrial Electricals, Transformers, Wires & Cables",
      "Solar Panels & Solar Systems",
      "Inverters, UPS & Battery",
      "Electrical Service Center",
    ],
    "Gifting": [
      "Toys, Books & Stationery Gift Stores",
      "Gift Hampers, Chocolates & Tray Decoration",
      "Florists & Flower Decoration",
      "Home Decor & Home Furnishings",
    ],
    "Laptops, Mobiles & Computers": [
      "Laptops, Printers, Computer Hardware & Accessories",
      "Inverters, UPS & Battery",
      "Mobile Phone & Accessories Stores",
      "Laptops, Printers, Computers Service Center",
      "Inverters, UPS, Battery Services Center",
      "Mobile Phone Services Center",
    ],
    "IT Services, Printing, Advertising & Marketing": [
      "Digital Marketing & Website/App Development",
      "Advertising & PR Agencies",
      "Flex Printing & Signage Boards",
      "Offset & Digital Printing",
      "Photocopy, Lamination & Binding",
      "Broadband, Internet Service Providers",
    ],
    "Security & Surveillance": [
      "Security Guards & Security Agencies",
      "CCTV, Home Automation & Security Systems",
      "Fire Fighting Solution",
    ],    //7
    "Clothing & Fashion": [
      "Ladies Wear",
      "Sarees, Lehengas & Bridal Wear",
      "Boutiques & Tailoring",
      "Children Clothing & Baby Care",
      "Men’s Formal Clothing & Party Wear",
      "Men’s Wear",
      "Inner Garments",
      "Hosiery & Garments",
      "Footwear",
      "Eyewear & Sunglasses",
      "Wrist Watches",
      "Handbags & Purses",
      "Luggage & Trolley Bags",
      "Cosmetics & Beauty Products",
      "Cloth & Fabric",
      "Jeans, T-shirts, Jackets, Shirts",
    ],
    "Consultants & Professionals": [
      "Architects",
      "Astrologers",
      "Vastu Experts",
      "Interior Designers",
      "Lawyers",
      "Career Counsellors",
      "Civil & Structural Engineers",
      "CA, Accountants & Tax Consultants",
      "Investment Advisors - Mutual Funds & Insurance",
      "Modular Kitchens",
      "Gym Trainer",
      "Yoga Expert",
      "Pandit",
      "NGO"
    ], //9

    "Construction Materials": [
      "Acids & Chemicals Store",
      "ACP Sheets",
      "TMT Steel, Iron Rods",
      "Steel & Iron Works",
      "Bricks and AAC Blocks",
      "Doors & Windows",
      "Boundary Fencing",
      "Generator, Cranes & Construction Machines",
      "Glass & Mirrors",
      "HVAC - Heating, Ventilation & Air Conditioning",
      "Lifts & Elevators",
      "Fire Fighting Solution",
      "POP Gypsum Sheets - False Ceiling",
      "Sanitary Bath, Water Tanks, Pipes & Fittings Material",
      "Pavers, Cement & Stone Tiles",
      "Wooden Flooring",
      "Vitrified, Tile & Wall Tiles",
      "Granite & Marble",
      "Waterproofing Solution Material",
      "Plumbing Material",
      "Wiring Material",
      "Construction Tools & Hardware Items",
      "Borewell & Samar sevel Pump store",
      "Cement, Iron Rods, Sand, Gravel and stone",
      "Roofing Sheet",
      "Wallpaper and wallpanels"
    ], //10
    "Contractors": [
      "Civil Construction, PMC & Renovation Contractors",
      "Electricians & Electrical Contractors",
      "Plumbers & Plumbing Contractors",
      "Flooring Contractors",
      "Painters & Painting Contractors",
      "Carpenters",
      "POP Contractors",
      "Marble & Tiles Contractors",
      "Waterproofing Contractors",
      "Soil filling Contractors",
      "Steel & Iron Works Contractors",
      "Labor Contractors",
      "Modular Kitchen Contractors"
    ],
    "Education, Coaching & Training": [
      "CA-CS Coaching",
      "Career Counsellors",
      "Colleges & Institutes",
      "Computer Training Institutes",
      "IPS, UPSC, Bank PO & SSC Coaching",
      "MBA Coaching",
      "Play Schools & Day Care",
      "School Tuition & Coaching Classes",
      "Schools",
      "Language Classes",
      "Car Driving Schools & Training Institutes",
      "ITI Institutes",
      "Polytechnic Institutes",
      "Ethical Hacking Institutes",
      "Website & App Designing Institutes",
      "Books & Stationery Stores",
      "Library",
      "Boys PG - Hostel",
      "Girls PG - Hostel",
    ],
    "Hobby Classes": [
      "Art Classes",
      "Dance Classes",
      "Music Classes",
      "Sports Classes",
      "Swimming Classes",
      "Musical Instrument Classes",
      "Boutique & Tailoring Classes",
      "Embroidery & Sewing(Silai) Classes",
      "Parlour Classes",
      "Judo & Karate Classes",
    ],  //13
    "Furniture & Plywood": [
      "Furniture Shops",
      "Plywood Shops",
      "Furniture Fittings & Hardware Shops",
      "Timber Cutting Center",
      "Commercial Furniture",
      "Furniture for Home",
      "Carpenters",
      "Wood Carving Center"
    ],
    "Party & Events, Weddings": [
      "Party/Event Planners",
      "Banquet, Party Halls & Lawns",
      "Hotels & Resorts",
      "Caterors",
      "Tent House, Light & Decorators",
      "Florists & Flower Decoration",
      "DJ & Sound Decoration",
      "Orchestra Party",
      "Dancers & Dance Party Supplies",
      "Drinking Water & Cold Drink",
      "Liquor, Alcohol & Wine Services",
      "Disposable Plastic & Paper Items",
      "Marriage Bureau & Matrimony Services",
      "Photo Studios & Photographers",
      "Festival, Rituals & Worship Needs",
      "Mehandi Artists",
      "Bridal Makeup Artists",
      "Party Decoration & Decoration Item Suppliers",
      "Balloon Decoration"
    ],
    "Salon, Beauty Parlour & Spa": [
      "Make-up Artists, Studios & Beauty Salons",
      "Men's Salon",
      "Massage & Spa Parlours",
      "Cosmetics & Beauty Products",
      "Mehandi Artists",
      "Tatto Artists"
    ],
    "Restaurants, Food & Drink": [
      "Restaurants & Cafes",
      "Chai cold Coffee Stores",
      "Street Food & Fast Food",
      "Bakery Shops & Cake Delivery",
      "Ice-Cream Parlours",
      "Sweets & Mithai Shops",
      "Paan Shops"
      "Juice Shops",
      "Liquor, Alcohol & Wine Shops"
    ],//17
    "Travel & Tourism": [
      "Travel Agents & Tour Operators",
      "Bike, Taxi & Bus on Rent",
      "Hotels & Resorts",
      "Serviced Apartments & Guesthouse",
      "Luggage & Trolley Bags"
    ],
    "Fun & Entertainment": [
      "Bars, Clubs & Lounges",
      "Water Park & Museum",
      "Game-Zone & Amusement Parks",
      "Movie Theatres & Live Shows"
    ],//19
    "Jewellery": [
      "Artificial Jewellery & Fashion Accessories",
      "Gold & Diamond Jewellery",
      "Silver & Platinum Jewellery"
    ],
    "Couriers, Transport & Logistics": [
      "Couriers & Home Delivery",
      "Packers & Movers",
      "Tempos, Trucks & Containers, Transport Services"
    ],
    "Financial Services": [
      "Banks, Loans & Currency Exchange",
      "Investment Advisors - Mutual Funds & Insurance",
      "CA, Accountants & Tax Consultants"
    ],
    "Real Estate": [
      "Property Dealers & Land Brokers",
      "Builders & Developers"
    ],
    "Cars,Bikes & Automobiles": [
      "Car Dealers & Service Center",
      "Rick Dealers & Service Center",
      "Auto Dealers & Service Center",
      "Commercial Vehicle Dealers",
      "Electric Vehicle Dealers & Service Center",
      "Bicycle Shops",
      "Car Accessories & Car Detailing",
      "Car Wash, Workshop",
      "Motorcycle Accessories",
      "Tyre Dealers",
      "Tractors, Farming Machines, Tools & Equipment"
    ],//24
    "Doctors, Clinics & Hospitals": [
      "Child Specialist Pediatrician",
      "General Physicians (cough, cold, pain, fever doctors)",
      "Dentists & Dental Clinics",
      "Skin & Hair Treatment",
      "Eye Doctors & Clinics",
      "Physiotherapy",
      "MRI, X-Ray, Ultrasound Imaging & Diagnostic Centres",
      "Blood Test & Path Labs",
      "Dietician & Nutritionists",
      "Gynaecologists & Obstetricians",
      "Homeopathy",
      "Ayurveda & Naturopathy Treatment",
      "Home Nurse, Baby Sitters & Domestic Help",
      "Hospitals & Clinics",
      "Pharmacy, Chemists & Medical Stores",
      "Veterinary Clinics",
      "IVF & Fertility Treatment",
      "ENT (Ear, Nose & Throat) Specialists",
      "Psychiatrists & Psychologists",
      "Speech Therapy & Hearing Clinics",
      "Artificial limb centre"
    ],
    "Health, Fitness & Sports": [
      "Gyms & Fitness Centres",
      "Sports Goods & Fitness Equipment",
      "Sports Coaching",
      "Yoga & Meditation Classes",
    ],
    "Business Needs & Supplies": [
      "Disposable Items manufacturers & supplies",
      "Construction Material Suppliers",
      "Legal Documents & Licenses",
      "Packing & Packaging Materials Suppliers",
      "Photocopy, Lamination & Binding Materials Suppliers",
      "Job & Placement Agencies",
      "Raw Material Suppliers",
      "Machine and Equipment Manufacturers & suppliers",
      "Autoparts manufacturers & suppliers",
      "Wholesale Goods Traders & Suppliers",
      "Acids & Chemicals Manufacturers & Suppliers",
      "Artificial limb equipment manufacturers & suppliers",
      "Oxygen and Medical Equipment Manufacturers & Suppliers",
      "Plumbing Items Manufacturers & Suppliers",
      "Electrical Items Manufacturers & Suppliers",
      "Cosmetic Items Manufacturers & Suppliers",
      "Paint manufacturers & suppliers",
      "PVC Items Manufacturers & Suppliers",
      "Leather items manufacturers & suppliers",
      "Toy Manufacturers & Suppliers",
      "Hosiery and Garments Manufacturers & Suppliers",
      "Electronic Items Manufacturers & Suppliers",
      "Printing Material Suppliers & Manufacturers",
      "Paper Supplies & Manufacturers",
      "Pharmacy, Chemists & Medical Suppliers",
      "Books, Stationery Manufacturers & Suppliers",
      "Farming Machines, Equipments Manufacturers & Suppliers",
      "Hotel & Restaurant Supplies",
      "Fruits & Vegetable Wholesaler",
    ],//26
    "Repairs & Service": [
      "Car Wash, Workshop, Repair & Service",
      "Camera Repair & Services"
      "Bicycle Shops & Repair",
      "Motorcycle Repair Service",
      "Auto Repair & Service",
      "Commercial Vehicle Repair & Service",
      "Tractors, Farming Machines Repair & Service",
      "Electric Vehicle Repair & Service",
      "Electrical & Electrotechnic Repair",
      "Home Appliances & Electronic Repair",
      "Laptops, Printers, Computers Repair & Networking",
      "DTH, TV, LED Repair & Service",
      "Mobile Repair & Service",
      "Samar sevel Pump Repair & Service",
      "Motor Repair & Service",
      "Vehicle Washing Service",
      "Sound System Repair & Service",
      "Inverters, UPS & Battery Repair & Service",
      "AC Repair & Service",
      "Fridge, Washing Machine Repair & Service",
      "Lathe Machine Workers",
      "Sewing Machine Repair",
      "Jcb Repair & Services",
    ],
    "Kids & Children": [
      "Babycare Product Stores",
      "Child Specialist - Pediatrician",
      "Toys & Stationery Stores",
      "Game-Zone & Amusement Parks",
    ],
    "Farming, Plants, Flowers & Pets": [
      "Nursery - Plants & Garden",
      "Florists & Flowers",
      "Pet Shops & Animal Food Shops",
      "Seeds, Fertilizers & Pesticides",
      "Veterinary Clinics & Medical Store",
      "Tractors, Farming Machines, Tools & Equipments"
    ]
  };

  final List<String> worker_type = [
    "Raj Mistri",
    "Labor",
    "Shuttering",
    "Net Binder",
    "Electrician",
    "Laundry",
    "Cleaner",
    "Cook",
    "Washer",
    "Care Takers",
    "Gardener",
    "Baby Sitter",
    "Home Nurse",
    "Driver",
    "Car Washer",
    "Boot Maker",
    "Home Worker",
    "Home Tutor",
    "Washer Man",
    "Others"
  ];

  final List<String> days=["Mon","Tues","Wed","Thurs","Fri","Sat","Sun"];
}
