// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtkTprbEwzACnmjmtoAuOgFv9cJyDN5As',
    appId: '1:923073096518:web:6eda95fd76d5e49a831347',
    messagingSenderId: '923073096518',
    projectId: 'amuserinfo-f94c5',
    authDomain: 'amuserinfo-f94c5.firebaseapp.com',
    storageBucket: 'amuserinfo-f94c5.firebasestorage.app',
    measurementId: 'G-ESK7BQ7JB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMZk4POrDjKxOTmLB3XOxjiQ4OswNgVbo',
    appId: '1:923073096518:android:225b0395d59c20c8831347',
    messagingSenderId: '923073096518',
    projectId: 'amuserinfo-f94c5',
    storageBucket: 'amuserinfo-f94c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOujRZbfw6xJ1XWOdqBeDnHoWImaE5Iyk',
    appId: '1:923073096518:ios:50ce73a0810fe362831347',
    messagingSenderId: '923073096518',
    projectId: 'amuserinfo-f94c5',
    storageBucket: 'amuserinfo-f94c5.firebasestorage.app',
    iosBundleId: 'com.example.amUser',
  );
}
